
title: Jonathan Leung
url: 'https://joleunggithub.github.io/'
baseurl: ''


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Jonathan Leung
tagline: Student
pic: JLogoSmallSquare.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: jo.leung@mail.utoronto.ca
website: writingisadrag.wordpress.com #do not add http://
linkedin: jocleung
github: JoLeungGitHub
twitter: '@LeungTweet'
facebook: jonathan.leung8
