- name: Twitter DM Bot
  link: https://goo.gl/yOeJoj
  description: Bot created in JavaScript to learn the basics of the twitter API and Node.js
  
- name: Twitter Data
  link: https://goo.gl/6z09Js
  description: Program created in python to read through "Twitter Data files"
  
- name: DNA Strand
  link: https://goo.gl/QHClQv
  description: Program created in python to analyse and modify "DNA Strands"
